import {getChatGPTUser} from '../../chatgpt-auth';
import {areas} from '../../shared';
import {database,sameOrigin,fail} from '../helpers';
import {z} from 'zod';
export const dynamic='force-dynamic';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s);
const schema=z.object({name:z.string().trim().min(2).max(80),title:z.string().trim().min(2).max(120),email:z.string().email().max(254),linkedin:z.string().url().max(300).refine(s=>{const u=new URL(s);return u.protocol==='https:'&&['linkedin.com','www.linkedin.com'].includes(u.hostname)&&/^\/in\/[^/]+\/?$/.test(u.pathname)},'Use a LinkedIn profile URL'),area:z.string().refine(s=>areas.some(a=>a.name===s)),status:z.enum(['resident','visitor']),arrival:date.optional(),departure:date.optional(),consent:z.literal('yes'),australian:z.literal('yes')}).refine(p=>p.status!=='visitor'||(p.arrival&&p.departure&&p.arrival<=p.departure),'Enter a valid arrival and departure date');
export async function GET(){try{const db=database();const now=Date.now();const today=new Date().toISOString().slice(0,10);const data=await db.prepare('SELECT id,name,title,email,linkedin,CASE WHEN area IN (\'Inner Richmond\',\'Outer Richmond\') THEN \'Richmond\' ELSE area END AS area,status,arrival,departure FROM profiles WHERE suspended_until <= ? AND (status = ? OR (arrival <= ? AND departure >= ?)) ORDER BY name').bind(now,'resident',today,today).all();return Response.json({profiles:data.results},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return fail('The directory is temporarily unavailable.',503)}}
export async function POST(r:Request){if(!sameOrigin(r))return fail('Request origin rejected.',403);const user=await getChatGPTUser();if(!user)return fail('Please sign in with ChatGPT before saving your profile.',401);try{const parsed=schema.safeParse(await r.json());if(!parsed.success)return fail(parsed.error.issues[0].message);const p=parsed.data;await database().prepare('INSERT INTO profiles (id,name,title,email,linkedin,area,status,arrival,departure,created_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,title=excluded.title,email=excluded.email,linkedin=excluded.linkedin,area=excluded.area,status=excluded.status,arrival=excluded.arrival,departure=excluded.departure').bind(user.userId,p.name,p.title,p.email,p.linkedin,p.area,p.status,p.status==='visitor'?p.arrival:null,p.status==='visitor'?p.departure:null,Date.now()).run();return Response.json({ok:true});}catch(e){console.error(e);return fail('Could not save. Your form is still here; please try again.',503)}}
export async function DELETE(r:Request){if(!sameOrigin(r))return fail('Request origin rejected.',403);const user=await getChatGPTUser();if(!user)return fail('Sign in to remove your profile.',401);try{await database().prepare('DELETE FROM profiles WHERE id = ?').bind(user.userId).run();return Response.json({ok:true})}catch{return fail('Could not remove your profile.',503)}}
