'use client';
import {useState} from 'react';
import copy from '../../content/community.json';
import KangarooLogo from '../kangaroo-logo';
import {Button} from '@/components/ui/button';
export default function About(){
 const [message,setMessage]=useState('');
 async function removeProfile(){if(!confirm('Remove your profile from the directory?'))return;try{const r=await fetch('/api/profiles',{method:'DELETE'});const d:any=await r.json();setMessage(r.ok?'Your profile has been removed.':d.error)}catch{setMessage('Could not remove your profile. Please try again.')}}
 return <><header className="topbar"><div className="brand-group"><KangarooLogo/></div><nav className="header-right"><a className="community-nav" href="/">Back to the map ↗</a></nav></header><main className="community-page"><div className="community-kicker">[ AU → SF ] <span>Community & open source</span></div><h1>{copy.title}</h1><p className="community-intro">{copy.intro}</p><a className="edit-copy" href="https://github.com/jx-lingson/aussies-in-sf/edit/main/content/community.json" target="_blank" rel="noreferrer">Edit this page’s copy ↗</a><div className="community-sections">{copy.sections.map((section,i)=><section className="community-section" key={section.heading}><span className="section-number">[{String(i+1).padStart(2,'0')}]</span><div><h2>{section.heading}</h2><p>{section.body}</p></div></section>)}</div><div className="community-actions"><a href="https://github.com/jx-lingson/aussies-in-sf" target="_blank" rel="noreferrer">{copy.sourceLinkLabel} ↗</a><Button variant="outline" onClick={removeProfile}>{copy.removeProfileLabel}</Button></div><p role="status">{message}</p><footer className="community-credits"><p>{copy.credits}</p><p><a href="https://poly.pizza/m/7uiVArqEC80">“Kangaroo” by Poly by Google</a>, <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>. Adapted with blue materials and interactive rotation.</p><p>Rotation inspired by <a href="https://anthonywang.dev/">Anthony Wang’s site</a>.</p></footer></main></>
}
