'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {areas,type Profile} from './shared';
export default function CompanyForm({onClose,onSaved,notify}:{onClose:()=>void;onSaved:(area?:string)=>Promise<void>;notify:(s:string)=>void}){
 const [mine,setMine]=useState<Profile|null>(null),[shareLink,setShareLink]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){const r=await fetch('/api/companies?mine=1');const d:any=await r.json();if(!r.ok)throw Error(d.error);setMine(d.company);setShareLink(d.company?location.origin+'/#company='+encodeURIComponent(d.company.id):'')}
 useEffect(()=>{load().catch(e=>notify(e.message)).finally(()=>setLoading(false))},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const body=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);await load();await onSaved(String(body.area));notify('Company saved. Use this browser to edit or remove it.')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
 async function remove(){if(!confirm('Remove your company from the map?'))return;setBusy(true);try{const r=await fetch('/api/companies',{method:'DELETE'});const d:any=await r.json();if(!r.ok)throw Error(d.error);await onSaved();onClose();notify('Company removed.')}catch(e:any){notify(e.message)}finally{setBusy(false)}}
 const star=<span className="required-mark" aria-hidden="true">*</span>;
 return <section className="join-form"><div className="section-title"><h2>{mine?'Your company':'Put your company on the map'}</h2><Button variant="ghost" aria-label="Close company form" onClick={onClose}>×</Button></div><p>Australian-founded or Australian-led, with a presence in the Bay. Suburb only.</p>{loading?<p>Loading…</p>:<>{mine&&<div className="profile-management"><p>Your company is saved.</p><label>Public company link<Input readOnly value={shareLink} onFocus={e=>e.target.select()}/></label><small>Share this link with anyone. Use this browser to edit or remove your company. Clearing browser data loses access.</small><Button variant="outline" onClick={()=>navigator.clipboard.writeText(shareLink).then(()=>notify('Public company link copied.')).catch(()=>notify('Select and copy the link above.'))}>Copy public link</Button></div>}<p className="required-note">{star} Required fields</p><form key={mine?JSON.stringify(mine):'new'} onSubmit={save}><label><span>Company name {star}</span><Input name="name" required minLength={2} maxLength={100} defaultValue={mine?.name}/></label><label><span>What does it do? {star}</span><textarea name="description" required minLength={5} maxLength={300} rows={3} defaultValue={mine?.title}/></label><label><span>Website {star}</span><Input name="website" type="url" required placeholder="https://yourcompany.com" defaultValue={mine?.website}/></label><label><span>Contact email <small>(optional)</small></span><Input name="email" type="email" defaultValue={mine?.email}/></label><label><span>Neighbourhood {star}</span><select name="area" required defaultValue={mine?.area||''}><option value="" disabled>Choose a neighbourhood</option>{areas.map(a=><option key={a.name}>{a.name}</option>)}</select></label><label className="check"><input name="australian" type="checkbox" value="yes" required defaultChecked={!!mine}/> This company is Australian-founded or Australian-led. {star}</label><label className="check"><input name="consent" type="checkbox" value="yes" required defaultChecked={!!mine}/> I’m authorised to list this company and publish these details. {star}</label><Button type="submit" className="join-button" disabled={busy}>{busy?'Saving…':mine?'Save changes':'Add company'}</Button><small>No account needed. This browser remembers your company.</small>{mine&&<Button type="button" variant="ghost" disabled={busy} onClick={remove}>Remove company</Button>}</form></>}</section>
}
