'use client';
import {useEffect,useRef,useState} from 'react';
import {areas as defaults,type Area} from './shared';
export default function SuburbField({value=''}:{value?:string}){
 const [areas,setAreas]=useState<Area[]>(defaults),[selected,setSelected]=useState(value),[point,setPoint]=useState<{lat:number;lng:number}|null>(null),[error,setError]=useState('');const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch('/api/areas').then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>setAreas(d.areas)).catch(()=>setError('Could not load added suburbs. Please refresh before choosing one.'))},[]);
 useEffect(()=>{if(selected!=='__custom')return;let map:any,disposed=false;const start=Date.now();const interval=setInterval(()=>{const L=(window as any).L;if(!L||!host.current){if(Date.now()-start>10000){clearInterval(interval);setError('The map could not load. Refresh to try again.')}return}clearInterval(interval);if(disposed)return;map=L.map(host.current,{zoomControl:true,scrollWheelZoom:false,minZoom:9,maxZoom:15,maxBounds:[[37.36,-122.57],[37.92,-122.08]],maxBoundsViscosity:1}).setView([37.76,-122.43],12);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'© Esri and contributors'}).addTo(map);let pin:any;const place=(lat:number,lng:number)=>{const p={lat:Math.round(lat*1000)/1000,lng:Math.round(lng*1000)/1000};setPoint(p);if(pin)pin.setLatLng(p);else pin=L.circleMarker(p,{radius:9,color:'#fff',fillColor:'#b89236',fillOpacity:1}).addTo(map)};map.on('click',(e:any)=>place(e.latlng.lat,e.latlng.lng));map.on('moveend',()=>{const c=map.getCenter();if(host.current)host.current.dataset.center=JSON.stringify({lat:c.lat,lng:c.lng})});host.current!.dataset.center=JSON.stringify({lat:37.76,lng:-122.43});},100);return()=>{disposed=true;clearInterval(interval);map?.remove()}},[selected]);
 return <div className="suburb-field"><label><span>Neighbourhood <span className="required-mark">*</span></span><select name="area" required value={selected} onChange={e=>{setSelected(e.target.value);setPoint(null)}}><option value="" disabled>Choose a neighbourhood</option>{value&&!areas.some(a=>a.name===value)&&<option value={value}>{value}</option>}{areas.map(a=><option key={a.name}>{a.name}</option>)}<option value="__custom">+ Add a suburb</option></select></label>{selected==='__custom'&&<div className="custom-suburb"><label>Suburb name <span className="required-mark">*</span><input name="customName" required minLength={2} maxLength={60} placeholder="e.g. NoPa"/></label><label>Region <span className="required-mark">*</span><select name="customRegion" required><option>San Francisco</option><option>East Bay</option><option>Peninsula</option></select></label><p>Mark the neighbourhood’s centre, not your home. Pan and zoom, then tap the map or use its centre.</p><div ref={host} className="suburb-picker" aria-label="Choose neighbourhood centre"/><button type="button" className="sf-overview" onClick={()=>{const c=host.current?.dataset.center;if(c)setPoint(JSON.parse(c))}}>Use map centre</button><input type="hidden" name="customLat" value={point?.lat??''}/><input type="hidden" name="customLng" value={point?.lng??''}/><small>{point?'Centre selected. This suburb will be shared with the community when you save.':'Choose a centre before saving.'}</small></div>}{error&&<p role="alert">{error}</p>}</div>
}
