import {resolveArea} from '../neighbourhoods';
import {z} from 'zod';
import {areas} from '../../shared';
import {database,fail,sameOrigin} from '../helpers';
import {digest,newToken,validToken} from '../ownership';
export const dynamic='force-dynamic';
const schema=z.object({name:z.string().trim().min(2).max(100),description:z.string().trim().min(5).max(300),website:z.string().url().max(300).refine(s=>new URL(s).protocol==='https:','Use an https website URL').transform(s=>new URL(s).origin),email:z.union([z.string().trim().email().max(254),z.literal('')]).default(''),area:z.string().min(1),australian:z.literal('yes'),consent:z.literal('yes')});
function token(r:Request){const v=r.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('aussies_company='))?.slice(16);return validToken(v)?v:null}
function cookie(r:Request,t:string){return `aussies_company=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000${new URL(r.url).protocol==='https:'?'; Secure':''}`}
async function mine(r:Request){const t=token(r);if(!t)return null;return database().prepare('SELECT * FROM companies WHERE owner_key=?').bind(await digest(t)).first<any>()}
function publicCompany(p:any){return {id:p.id,name:p.name,title:p.description,website:p.website,email:p.email,area:p.area,status:'company',linkedin:p.website,kind:'company'}}
export async function GET(r:Request){try{if(new URL(r.url).searchParams.has('mine')){const p=await mine(r);return Response.json({company:p?publicCompany(p):null},{headers:{'Cache-Control':'no-store'}})}const rows=await database().prepare('SELECT id,name,description,website,email,area FROM companies ORDER BY name').all();return Response.json({companies:rows.results.map(publicCompany)},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return fail('Could not load companies.',503)}}
export async function POST(r:Request){if(!sameOrigin(r))return fail('Request origin rejected.',403);try{const body:any=await r.json();const parsed=schema.safeParse(body);if(!parsed.success)return fail(parsed.error.issues[0].message);let resolved;try{resolved=await resolveArea(body)}catch(e){return fail(e instanceof Error?e.message:'Choose a valid neighbourhood centre.')}const p={...parsed.data,area:resolved.name},owned=await mine(r),id=owned?.id||crypto.randomUUID(),t=owned?token(r)!:newToken();const existing=await database().prepare('SELECT id FROM companies WHERE website=? AND id!=?').bind(p.website,id).first();if(existing)return fail('This company is already listed. Use the browser where you created it to manage it.',409);const write=database().prepare('INSERT INTO companies(id,name,description,website,email,area,owner_key,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,website=excluded.website,email=excluded.email,area=excluded.area').bind(id,p.name,p.description,p.website,p.email,p.area,await digest(t),Date.now());await database().batch(resolved.statement?[resolved.statement,write]:[write]);return Response.json({ok:true,area:p.area},{headers:{'Set-Cookie':cookie(r,t),'Cache-Control':'no-store'}})}catch(e){console.error(e);return fail('Could not save your company. Please try again.',503)}}
export async function DELETE(r:Request){if(!sameOrigin(r))return fail('Request origin rejected.',403);try{const p=await mine(r);if(!p)return fail('Use the browser where you created this company.',401);await database().prepare('DELETE FROM companies WHERE id=?').bind(p.id).run();return Response.json({ok:true})}catch{return fail('Could not remove the company.',503)}}
